### ISSUE TITLE
动画的速度在哪里处理呢  求救

### ISSUE THREAD

**Issue by mjlxiaoma** [tsinghua-lau/one-step#2]

**Comment by mjlxiaoma** [comment]
![image](https://github.com/tsinghua-lau/one-step/assets/89441679/6468b201-19d3-4067-8b22-afcb03f8cd65)
zhe这个速度请问怎么处理呢

**Comment by mjlxiaoma** [comment]
麻烦回复一下

**Comment by tsinghua-lau** [comment]
> ![image](https://user-images.githubusercontent.com/89441679/237660118-6468b201-19d3-4067-8b22-afcb03f8cd65.png) zhe这个速度请问怎么处理呢

requestAnimationFrame是一个用于调度动画的JavaScript函数，你可以调整`step`的值来控制动画的移动速度。
